/*
 Navicat Premium Data Transfer

 Source Server         : postgreLocal
 Source Server Type    : PostgreSQL
 Source Server Version : 160000 (160000)
 Source Host           : localhost:5432
 Source Catalog        : ecommerce
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160000 (160000)
 File Encoding         : 65001

 Date: 12/12/2023 09:37:02
*/


-- ----------------------------
-- Sequence structure for Address_Customer_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Address_Customer_id_seq";
CREATE SEQUENCE "public"."Address_Customer_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for Cart_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Cart_id_seq";
CREATE SEQUENCE "public"."Cart_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for Comment_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Comment_id_seq";
CREATE SEQUENCE "public"."Comment_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for Customer_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Customer_id_seq";
CREATE SEQUENCE "public"."Customer_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for Employee_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Employee_id_seq";
CREATE SEQUENCE "public"."Employee_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for Job_Title_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Job_Title_id_seq";
CREATE SEQUENCE "public"."Job_Title_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for Order_Detail_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Order_Detail_id_seq";
CREATE SEQUENCE "public"."Order_Detail_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for Order_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Order_id_seq";
CREATE SEQUENCE "public"."Order_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for Payment_Method_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Payment_Method_id_seq";
CREATE SEQUENCE "public"."Payment_Method_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for Product_Category_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Product_Category_id_seq";
CREATE SEQUENCE "public"."Product_Category_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for Product_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Product_id_seq";
CREATE SEQUENCE "public"."Product_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for Provider_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."Provider_id_seq";
CREATE SEQUENCE "public"."Provider_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Table structure for Address_Customer
-- ----------------------------
DROP TABLE IF EXISTS "public"."Address_Customer";
CREATE TABLE "public"."Address_Customer" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "customer_id" int4,
  "address_customer_name" varchar COLLATE "pg_catalog"."default",
  "phone_number" varchar COLLATE "pg_catalog"."default",
  "city" varchar COLLATE "pg_catalog"."default",
  "district" varchar COLLATE "pg_catalog"."default",
  "sub_district" varchar COLLATE "pg_catalog"."default",
  "address" varchar COLLATE "pg_catalog"."default",
  "is_deleted" bool
)
;

-- ----------------------------
-- Table structure for Cart
-- ----------------------------
DROP TABLE IF EXISTS "public"."Cart";
CREATE TABLE "public"."Cart" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "customer_id" int4,
  "product_id" int4,
  "quantity" int4,
  "unit_price" numeric,
  "is_deleted" bool
)
;

-- ----------------------------
-- Table structure for Comment
-- ----------------------------
DROP TABLE IF EXISTS "public"."Comment";
CREATE TABLE "public"."Comment" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "customer_id" int4,
  "product_id" int4,
  "content" varchar COLLATE "pg_catalog"."default",
  "rating" int4,
  "comment_image" varchar COLLATE "pg_catalog"."default",
  "is_deleted" bool
)
;

-- ----------------------------
-- Table structure for Customer
-- ----------------------------
DROP TABLE IF EXISTS "public"."Customer";
CREATE TABLE "public"."Customer" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "first_name" varchar COLLATE "pg_catalog"."default",
  "last_name" varchar COLLATE "pg_catalog"."default",
  "email" varchar COLLATE "pg_catalog"."default",
  "password" varchar COLLATE "pg_catalog"."default",
  "phone_number" varchar COLLATE "pg_catalog"."default",
  "birth_date" date,
  "gender" bool,
  "customer_image" varchar COLLATE "pg_catalog"."default",
  "is_deleted" bool
)
;

-- ----------------------------
-- Table structure for Employee
-- ----------------------------
DROP TABLE IF EXISTS "public"."Employee";
CREATE TABLE "public"."Employee" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "first_name" varchar COLLATE "pg_catalog"."default",
  "last_name" varchar COLLATE "pg_catalog"."default",
  "email" varchar COLLATE "pg_catalog"."default",
  "password" varchar COLLATE "pg_catalog"."default",
  "phone_number" varchar COLLATE "pg_catalog"."default",
  "birth_date" date,
  "gender" bool,
  "employee_image" varchar COLLATE "pg_catalog"."default",
  "address" varchar COLLATE "pg_catalog"."default",
  "hire_date" date,
  "job_title_id" int4,
  "salary" numeric,
  "is_deleted" bool
)
;

-- ----------------------------
-- Table structure for Job_Title
-- ----------------------------
DROP TABLE IF EXISTS "public"."Job_Title";
CREATE TABLE "public"."Job_Title" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "job_title_name" varchar COLLATE "pg_catalog"."default",
  "is_deleted" bool
)
;

-- ----------------------------
-- Table structure for Order
-- ----------------------------
DROP TABLE IF EXISTS "public"."Order";
CREATE TABLE "public"."Order" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "customer_id" int4,
  "employee_id" int4,
  "order_date_time" timestamp(6),
  "address_customer_id" int4,
  "total_price" numeric,
  "shipping_cost" numeric,
  "payment_method_id" int4,
  "order_status" varchar COLLATE "pg_catalog"."default",
  "is_deleted" bool
)
;

-- ----------------------------
-- Table structure for Order_Detail
-- ----------------------------
DROP TABLE IF EXISTS "public"."Order_Detail";
CREATE TABLE "public"."Order_Detail" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "order_id" int4,
  "product_id" int4,
  "quantity" int4,
  "unit_price" numeric,
  "is_deleted" bool
)
;

-- ----------------------------
-- Table structure for Payment_Method
-- ----------------------------
DROP TABLE IF EXISTS "public"."Payment_Method";
CREATE TABLE "public"."Payment_Method" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "payment_method_name" varchar COLLATE "pg_catalog"."default",
  "is_deleted" bool
)
;

-- ----------------------------
-- Table structure for Product
-- ----------------------------
DROP TABLE IF EXISTS "public"."Product";
CREATE TABLE "public"."Product" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "product_name" varchar COLLATE "pg_catalog"."default",
  "description" varchar COLLATE "pg_catalog"."default",
  "rating" numeric,
  "unit_price" numeric,
  "stock_quantity" int4,
  "product_image" varchar COLLATE "pg_catalog"."default",
  "product_category_id" int4,
  "provider_id" int4,
  "is_deleted" bool
)
;

-- ----------------------------
-- Table structure for Product_Category
-- ----------------------------
DROP TABLE IF EXISTS "public"."Product_Category";
CREATE TABLE "public"."Product_Category" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "product_category_name" varchar COLLATE "pg_catalog"."default",
  "is_deleted" bool
)
;

-- ----------------------------
-- Table structure for Provider
-- ----------------------------
DROP TABLE IF EXISTS "public"."Provider";
CREATE TABLE "public"."Provider" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "provider_name" varchar COLLATE "pg_catalog"."default",
  "is_deleted" bool
)
;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Address_Customer_id_seq"
OWNED BY "public"."Address_Customer"."id";
SELECT setval('"public"."Address_Customer_id_seq"', 1, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Cart_id_seq"
OWNED BY "public"."Cart"."id";
SELECT setval('"public"."Cart_id_seq"', 1, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Comment_id_seq"
OWNED BY "public"."Comment"."id";
SELECT setval('"public"."Comment_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Customer_id_seq"
OWNED BY "public"."Customer"."id";
SELECT setval('"public"."Customer_id_seq"', 1, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Employee_id_seq"
OWNED BY "public"."Employee"."id";
SELECT setval('"public"."Employee_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Job_Title_id_seq"
OWNED BY "public"."Job_Title"."id";
SELECT setval('"public"."Job_Title_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Order_Detail_id_seq"
OWNED BY "public"."Order_Detail"."id";
SELECT setval('"public"."Order_Detail_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Order_id_seq"
OWNED BY "public"."Order"."id";
SELECT setval('"public"."Order_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Payment_Method_id_seq"
OWNED BY "public"."Payment_Method"."id";
SELECT setval('"public"."Payment_Method_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Product_Category_id_seq"
OWNED BY "public"."Product_Category"."id";
SELECT setval('"public"."Product_Category_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Product_id_seq"
OWNED BY "public"."Product"."id";
SELECT setval('"public"."Product_id_seq"', 1, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."Provider_id_seq"
OWNED BY "public"."Provider"."id";
SELECT setval('"public"."Provider_id_seq"', 11, true);

-- ----------------------------
-- Primary Key structure for table Address_Customer
-- ----------------------------
ALTER TABLE "public"."Address_Customer" ADD CONSTRAINT "Address_Customer_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table Cart
-- ----------------------------
ALTER TABLE "public"."Cart" ADD CONSTRAINT "Cart_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table Comment
-- ----------------------------
ALTER TABLE "public"."Comment" ADD CONSTRAINT "Comment_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table Customer
-- ----------------------------
ALTER TABLE "public"."Customer" ADD CONSTRAINT "Customer_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table Employee
-- ----------------------------
ALTER TABLE "public"."Employee" ADD CONSTRAINT "Employee_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table Job_Title
-- ----------------------------
ALTER TABLE "public"."Job_Title" ADD CONSTRAINT "Job_Title_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table Order
-- ----------------------------
ALTER TABLE "public"."Order" ADD CONSTRAINT "Order_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table Order_Detail
-- ----------------------------
ALTER TABLE "public"."Order_Detail" ADD CONSTRAINT "Order_Detail_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table Payment_Method
-- ----------------------------
ALTER TABLE "public"."Payment_Method" ADD CONSTRAINT "Payment_Method_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table Product
-- ----------------------------
ALTER TABLE "public"."Product" ADD CONSTRAINT "Product_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table Product_Category
-- ----------------------------
ALTER TABLE "public"."Product_Category" ADD CONSTRAINT "Product_Category_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table Provider
-- ----------------------------
ALTER TABLE "public"."Provider" ADD CONSTRAINT "Provider_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table Address_Customer
-- ----------------------------
ALTER TABLE "public"."Address_Customer" ADD CONSTRAINT "Address_Customer_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."Customer" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table Cart
-- ----------------------------
ALTER TABLE "public"."Cart" ADD CONSTRAINT "Cart_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."Customer" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."Cart" ADD CONSTRAINT "Cart_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."Product" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table Comment
-- ----------------------------
ALTER TABLE "public"."Comment" ADD CONSTRAINT "Comment_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."Customer" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."Comment" ADD CONSTRAINT "Comment_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."Product" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table Employee
-- ----------------------------
ALTER TABLE "public"."Employee" ADD CONSTRAINT "Employee_job_title_id_fkey" FOREIGN KEY ("job_title_id") REFERENCES "public"."Job_Title" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table Order
-- ----------------------------
ALTER TABLE "public"."Order" ADD CONSTRAINT "Order_address_customer_id_fkey" FOREIGN KEY ("address_customer_id") REFERENCES "public"."Address_Customer" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."Order" ADD CONSTRAINT "Order_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "public"."Customer" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."Order" ADD CONSTRAINT "Order_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "public"."Employee" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."Order" ADD CONSTRAINT "Order_payment_method_id_fkey" FOREIGN KEY ("payment_method_id") REFERENCES "public"."Payment_Method" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table Order_Detail
-- ----------------------------
ALTER TABLE "public"."Order_Detail" ADD CONSTRAINT "Order_Detail_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."Order" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."Order_Detail" ADD CONSTRAINT "Order_Detail_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."Product" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table Product
-- ----------------------------
ALTER TABLE "public"."Product" ADD CONSTRAINT "Product_product_category_id_fkey" FOREIGN KEY ("product_category_id") REFERENCES "public"."Product_Category" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."Product" ADD CONSTRAINT "Product_provider_id_fkey" FOREIGN KEY ("provider_id") REFERENCES "public"."Provider" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
